### ISSUE TITLE
Add documentation translations

### ISSUE THREAD

**Issue by thibaudcolas** [thibaudcolas/draftail.org#18]
Docusaurus supports documentation translations with Crowdin – see https://docusaurus.io/docs/en/translation. It would be really cool for the Draftail docs to use this – not necessarily for the whole site, but at least for the user guide: https://www.draftail.org/docs/user-guide.

Tasks:

- [ ] Set up Crowdin
- [ ] Configure translations
  - https://docusaurus.io/docs/en/site-config#useenglishurl-string
- [ ] Add language picker in menu
- [ ] Translate user guide in a few languages (2-3)
- [ ] Check migration requirements / redirects when deploying this
- [ ] Check compatibility with docs versioning
- [ ] Blog post
